In [10]:
import tensorflow as tf
print(tf.__version__)
import os

2.11.0


In [4]:
daily_sales_numbers = [21, 22, -108, 31, -1, 32, 34,31]
print("daily_sales_numbers is of type: ", type(daily_sales_numbers))

daily_sales_numbers is of type:  <class 'list'>


In [5]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)
print("tf_dataset is: ", tf_dataset)
print("tf_dataset is of type: ", type(tf_dataset))


tf_dataset is:  <TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>
tf_dataset is of type:  <class 'tensorflow.python.data.ops.from_tensor_slices_op.TensorSliceDataset'>


In [33]:
images_ds = tf.data.Dataset.list_files('LeavesImages/*/*', shuffle=False)
image_count = len(images_ds)
image_count

2152

In [34]:
for file in images_ds.take(3):
    print(file.numpy())

b'LeavesImages\\Potato___Early_blight\\001187a0-57ab-4329-baff-e7246a9edeb0___RS_Early.B 8178.JPG'
b'LeavesImages\\Potato___Early_blight\\002a55fb-7a3d-4a3a-aca8-ce2d5ebc6925___RS_Early.B 8170.JPG'
b'LeavesImages\\Potato___Early_blight\\009c8c31-f22d-4ffd-8f16-189c6f06c577___RS_Early.B 7885.JPG'


In [35]:
def get_label(file_path):
    parts = tf.strings.split(file_path, os.path.sep)
    return parts[-2]

In [37]:
get_label("LeavesImages\\Potato___Early_blight\\001187a0-57ab-4329-baff-e7246a9edeb0___RS_Early.B 8178.JPG")

<tf.Tensor: shape=(), dtype=string, numpy=b'Potato___Early_blight'>

In [29]:
# tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)
# print("tf_dataset is of type: ", type(tf_dataset))
# for elements in tf_dataset:
#     print(elements)
#     print("elements is of type: ", type(elements))
# tf_dataset_mapped = tf_dataset.map(lambda x: x*72)
# print("tf_dataset is of type: ", type(tf_dataset_mapped))
# for sales in tf_dataset_mapped:
#     print(sales)
#     print("sales is of type: ", type(sales))


tf_dataset is of type:  <class 'tensorflow.python.data.ops.from_tensor_slices_op.TensorSliceDataset'>


In [38]:
def process_image(file_path):
    label = get_label(file_path)
    img = tf.io.read_file(file_path) # load the raw data from the file as a string
    img = tf.image.decode_jpeg(img)
    img = tf.image.resize(img, [128, 128])
    return img, label

In [40]:
img, label = process_image("LeavesImages\\Potato___Early_blight\\001187a0-57ab-4329-baff-e7246a9edeb0___RS_Early.B 8178.JPG")

In [42]:
print("img is of type: ", type(img))
print("img is of type: ", type(label))

img is of type:  <class 'tensorflow.python.framework.ops.EagerTensor'>
img is of type:  <class 'tensorflow.python.framework.ops.EagerTensor'>


In [45]:
train_ds = images_ds.map(process_image)
print("train_ds is of type: ", type(train_ds))

train_ds is of type:  <class 'tensorflow.python.data.ops.dataset_ops.MapDataset'>


In [46]:
for image, label in train_ds.take(1):
    print("****",image)
    print("****",label)

**** tf.Tensor(
[[[140.5  137.5  144.5 ]
  [145.75 142.75 149.75]
  [139.75 136.75 143.75]
  ...
  [179.5  176.5  183.5 ]
  [179.75 176.75 183.75]
  [173.25 170.25 177.25]]

 [[141.5  138.5  145.5 ]
  [159.75 156.75 163.75]
  [140.5  137.5  144.5 ]
  ...
  [174.75 171.75 178.75]
  [174.25 171.25 178.25]
  [173.25 170.25 177.25]]

 [[147.75 144.75 151.75]
  [159.75 156.75 163.75]
  [147.   144.   151.  ]
  ...
  [173.25 170.25 177.25]
  [176.5  173.5  180.5 ]
  [180.75 177.75 184.75]]

 ...

 [[125.25 122.25 133.25]
  [125.75 122.75 133.75]
  [133.   130.   141.  ]
  ...
  [156.   155.   163.  ]
  [158.75 158.75 168.75]
  [161.75 161.75 171.75]]

 [[126.25 123.25 134.25]
  [118.   115.   126.  ]
  [120.   117.   128.  ]
  ...
  [157.   156.   164.  ]
  [158.5  158.5  168.5 ]
  [160.   160.   170.  ]]

 [[112.5  109.5  120.5 ]
  [126.75 123.75 134.75]
  [114.75 111.75 122.75]
  ...
  [156.5  155.5  163.5 ]
  [161.75 161.75 171.75]
  [166.25 166.25 178.25]]], shape=(128, 128, 3), dtype=fl