In [2]:
from sklearn.neighbors import KernelDensity
import numpy as np
rng = np.random.RandomState(42)
X = rng.random_sample((100, 3))
print(X.shape)

(100, 3)


In [3]:
print(X)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]
 [0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378]
 [0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159]
 [0.94888554 0.96563203 0.80839735]
 [0.30461377 0.09767211 0.68423303]
 [0.44015249 0.12203823 0.49517691]
 [0.03438852 0.9093204  0.25877998]
 [0.66252228 0.31171108 0.52006802]
 [0.54671028 0.18485446 0.96958463]
 [0.77513282 0.93949894 0.89482735]
 [0.59789998 0.92187424 0.0884925 ]
 [0.19598286 0.04522729 0.32533033]
 [0.38867729 0.27134903 0.82873751]
 [0.35675333 0.28093451 0.54269608]
 [0.14092422 0.80219698 0.07455064]
 [0.98688694 0.77224477 0.19871568]
 [0.00552212 0.81546143 0.70685734]
 [0.72900717 0.77127035 0.07404465]
 [0.35846573 0.11586906 0.86310343]
 [0.62329813 0.33089802 0.06

In [4]:
print(X[:3])

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [5]:
kde = KernelDensity(kernel='gaussian', bandwidth=0.5).fit(X)
log_density = kde.score_samples(X[:3])
log_density

array([-1.52955942, -1.51462041, -1.60244657])

In [6]:
kde = KernelDensity(kernel='gaussian', bandwidth=0.5).fit(X)
log_density = kde.score_samples(X)
log_density

array([-1.52955942, -1.51462041, -1.60244657, -1.90943146, -1.59670269,
       -1.33728666, -1.24975409, -1.41192172, -1.39081637, -1.45713084,
       -1.60225673, -1.89893904, -1.46982238, -1.3652277 , -1.74010106,
       -1.27394777, -1.64188774, -1.77293587, -1.64609499, -1.60855436,
       -1.40495369, -1.25467359, -1.69403848, -1.73916709, -1.66955114,
       -1.58847063, -1.56935179, -1.49583729, -1.32033012, -1.39749323,
       -1.50085343, -1.27114503, -1.48608102, -1.67085942, -1.44504612,
       -1.34079818, -1.56581228, -1.68870009, -1.51992483, -1.48849091,
       -1.56140409, -1.46400235, -1.82146727, -1.28192186, -1.65085179,
       -1.26001893, -1.79211661, -1.29105801, -1.5208851 , -1.51511015,
       -1.69269563, -1.56525609, -1.39427553, -1.3218243 , -1.42552581,
       -1.52304214, -1.48510966, -1.57313413, -1.42108942, -1.6057749 ,
       -1.64535552, -1.54139736, -1.34131095, -1.67777112, -1.47068393,
       -1.48821358, -1.53747025, -1.74455844, -1.74630882, -1.71