In [1]:
import torch

# Create the variable
x = torch.tensor(2 * torch.ones(2, 2), requires_grad=True)
print(x)

# Perform some operations involving x
y = x * 3
print(y)
# Call backward with -x as the argument
result = y.backward(-x)
print(result)
# Access the gradients of x
x_gradients = x.grad

print(x_gradients)  # Print the gradients of x

tensor([[2., 2.],
        [2., 2.]], requires_grad=True)
tensor([[6., 6.],
        [6., 6.]], grad_fn=<MulBackward0>)
None
tensor([[-6., -6.],
        [-6., -6.]])


<ipython-input-1-094f9d10e69b>:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(2 * torch.ones(2, 2), requires_grad=True)
